/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'decoder': EventHandler<never, { topic: 'frontend.rob.allocate'; data: never }>
    'global decoder': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'frontend.decode'; data: never }>
    'global rob': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'frontend.rob.allocate'; data: never }>
    'global rs': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'frontend.rs.dispatch'; data: never }>
    'reservation station': EventHandler<never, never>
    'rob': EventHandler<never, { topic: 'frontend.rs.dispatch'; data: never }>
  }
    
}