mod brk;
mod clock_gettime;
mod close;
mod exit;
mod fcntl;
mod fstat;
mod getcwd;
mod getrandom;
mod ioctl;
mod lseek;
mod mlock;
mod mmap;
mod mprotect;
mod openat;
mod prlimit64;
mod read;
mod readlinkat;
mod riscv_hwprobe;
mod rt_sigaction;
mod rt_sigprocmask;
mod set_robust_list;
mod tgkill;
mod write;
mod writev;

pub use brk::handle_brk;
pub use clock_gettime::handle_clock_gettime;
pub use close::handle_close;
pub use exit::handle_exit;
pub use fcntl::handle_fcntl;
pub use fstat::handle_fstat;
pub use getcwd::handle_getcwd;
pub use getrandom::handle_getrandom;
pub use ioctl::handle_ioctl;
pub use lseek::handle_lseek;
pub use mlock::{handle_mlock, handle_mlockall};
pub use mmap::handle_mmap;
pub use mprotect::handle_mprotect;
pub use openat::handle_openat;
pub use prlimit64::handle_prlimit64;
pub use read::handle_read;
pub use readlinkat::handle_readlinkat;
pub use riscv_hwprobe::handle_riscv_hwprobe;
pub use rt_sigaction::handle_rt_sigaction;
pub use rt_sigprocmask::handle_rt_sigprocmask;
pub use set_robust_list::handle_set_robust_list;
pub use tgkill::handle_tgkill;
pub use write::handle_write;
pub use writev::handle_writev;

mod dispatch;
pub use dispatch::{handle_syscall, handle_syscall_with_state};
