use std::path::{Path, PathBuf};
use std::process::Command;

/// Flash bitstream to FPGA using vdbg
pub struct FlashBitstreamStep {
    pub bitstream_path: PathBuf,
    pub fpga_location: String,
    pub output_dir: PathBuf,
}

impl FlashBitstreamStep {
    pub fn new(bitstream_path: impl Into<PathBuf>) -> Self {
        Self {
            bitstream_path: bitstream_path.into(),
            fpga_location: "0.A".to_string(),
            output_dir: PathBuf::from("./out"),
        }
    }

    pub fn fpga_location(mut self, location: impl Into<String>) -> Self {
        self.fpga_location = location.into();
        self
    }

    pub fn output_dir(mut self, dir: impl Into<PathBuf>) -> Self {
        self.output_dir = dir.into();
        self
    }

    pub fn run(&self) -> Result<(), String> {
        log::info!("Flashing bitstream to FPGA using vdbg...");
        log::info!("  Bitstream: {:?}", self.bitstream_path);
        log::info!("  FPGA Location: {}", self.fpga_location);
        log::info!("  Output Dir: {:?}", self.output_dir);

        if !self.bitstream_path.exists() {
            return Err(format!(
                "Bitstream not found: {}",
                self.bitstream_path.display()
            ));
        }

        if !self.output_dir.exists() {
            return Err(format!(
                "Output directory not found: {}",
                self.output_dir.display()
            ));
        }

        // Generate TCL script for vdbg
        let tcl_script = self.generate_vdbg_tcl();
        let tcl_path = self.output_dir.join("flash_bitstream.tcl");
        std::fs::write(&tcl_path, tcl_script)
            .map_err(|e| format!("Failed to write TCL script: {}", e))?;

        log::info!("Generated vdbg TCL script: {:?}", tcl_path);

        // Find sourceme.sh
        let sourceme = self.find_sourceme()?;
        log::info!("Using sourceme.sh: {:?}", sourceme);

        // Run vdbg with sourced environment
        // Use bash -c to source the environment and then run vdbg
        let cmd = format!(
            "source {} && cd {} && vdbg {}",
            sourceme.display(),
            self.output_dir.canonicalize()
                .map_err(|e| format!("Failed to canonicalize output_dir: {}", e))?
                .display(),
            tcl_path.file_name()
                .ok_or("Invalid TCL path")?
                .to_str()
                .ok_or("Invalid TCL filename")?
        );

        let status = Command::new("bash")
            .arg("-c")
            .arg(&cmd)
            .status()
            .map_err(|e| format!("Failed to execute vdbg: {}", e))?;

        if !status.success() {
            return Err("Bitstream flashing failed".to_string());
        }

        log::info!("Bitstream flashed successfully");
        Ok(())
    }

    fn find_sourceme(&self) -> Result<PathBuf, String> {
        // Try to find sourceme.sh in common locations
        let candidates = vec![
            PathBuf::from("sourceme.sh"),
            PathBuf::from("./sourceme.sh"),
            self.output_dir.join("../sourceme.sh"),
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sourceme.sh"),
        ];

        for path in candidates {
            if path.exists() {
                return Ok(path);
            }
        }

        Err("sourceme.sh not found. Please ensure sourceme.sh exists in the project directory".to_string())
    }

    fn generate_vdbg_tcl(&self) -> String {
        format!(
            r#"# Flash bitstream using vdbg
# Generated by bebop-p2e

# Load design from current directory
design .

# Connect to hardware server
hw_server . -location {}

# Download bitstream to FPGA
download

puts "Bitstream flashed successfully"
exit
"#,
            self.fpga_location
        )
    }
}
