# Rust 代码格式化配置文件 (仅稳定功能)
# 更多配置选项: https://rust-lang.github.io/rustfmt/

# 每行最大宽度
max_width = 120

# 硬标签宽度
tab_spaces = 2

# 使用字段初始化简写
use_field_init_shorthand = true

# 在小数组上使用小布局
use_small_heuristics = "Default"

# 匹配块尾随逗号
match_block_trailing_comma = true

# 换行风格
newline_style = "Unix"

# 版本
edition = "2021"

