pub mod bank_matrix;
pub mod decode;
#[path = "00_fence.rs"]
pub mod f00_fence;
#[path = "01_barrier.rs"]
pub mod f01_barrier;
#[path = "02_gemmini_config.rs"]
pub mod f02_gemmini_config;
#[path = "03_gemmini_flush.rs"]
pub mod f03_gemmini_flush;
#[path = "04_bdb_counter.rs"]
pub mod f04_bdb_counter;
#[path = "16_mvout.rs"]
pub mod f16_mvout;
#[path = "32_mset.rs"]
pub mod f32_mset;
#[path = "33_mvin.rs"]
pub mod f33_mvin;
#[path = "48_im2col.rs"]
pub mod f48_im2col;
#[path = "49_transpose.rs"]
pub mod f49_transpose;
#[path = "50_relu.rs"]
pub mod f50_relu;
#[path = "51_quant.rs"]
pub mod f51_quant;
#[path = "52_dequant.rs"]
pub mod f52_dequant;
#[path = "53_gemmini_preload.rs"]
pub mod f53_gemmini_preload;
#[path = "54_bdb_backdoor.rs"]
pub mod f54_bdb_backdoor;
#[path = "64_mul_warp16.rs"]
pub mod f64_mul_warp16;
#[path = "65_bfp.rs"]
pub mod f65_bfp;
#[path = "66_gemmini_compute_preloaded.rs"]
pub mod f66_gemmini_compute_preloaded;
#[path = "67_gemmini_compute_accumulated.rs"]
pub mod f67_gemmini_compute_accumulated;
#[path = "80_gemmini_loop_ws.rs"]
pub mod f80_gemmini_loop_ws;
#[path = "96_gemmini_loop_conv_ws.rs"]
pub mod f96_gemmini_loop_conv_ws;
pub mod gemmini_state;
