use crate::runner::{SimulationResult};
use std::path::PathBuf;
use std::process::Command;
use std::time::Duration;

/// Run complete P2E workflow: flash + init + workload
pub struct RunWorkloadStep {
    pub fpga_location: String,
    pub output_dir: PathBuf,
    pub image_path: PathBuf,
    pub ddr_channel: u32,
    pub timeout: Duration,
}

impl RunWorkloadStep {
    pub fn new(
        fpga_location: impl Into<String>,
        output_dir: impl Into<PathBuf>,
        image_path: impl Into<PathBuf>,
    ) -> Self {
        Self {
            fpga_location: fpga_location.into(),
            output_dir: output_dir.into(),
            image_path: image_path.into(),
            ddr_channel: 0,
            timeout: Duration::from_secs(300), // 5 minutes default
        }
    }

    pub fn ddr_channel(mut self, channel: u32) -> Self {
        self.ddr_channel = channel;
        self
    }

    pub fn timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    pub fn run(&self) -> Result<SimulationResult, String> {
        log::info!("Running complete P2E workflow using vdbg...");
        log::info!("  FPGA Location: {}", self.fpga_location);
        log::info!("  Output Dir: {:?}", self.output_dir);
        log::info!("  Image: {:?}", self.image_path);
        log::info!("  DDR Channel: {}", self.ddr_channel);

        // Validate paths
        self.validate_paths()?;

        // Generate main run.tcl script that orchestrates everything
        let tcl_script = self.generate_run_tcl();
        let tcl_path = self.output_dir.join("run.tcl");
        std::fs::write(&tcl_path, tcl_script)
            .map_err(|e| format!("Failed to write run.tcl: {}", e))?;

        log::info!("Generated run.tcl: {:?}", tcl_path);

        // Find sourceme.sh
        let sourceme = self.find_sourceme()?;
        log::info!("Using sourceme.sh: {:?}", sourceme);

        // Run vdbg with sourced environment
        let cmd = format!(
            "source {} && cd {} && vdbg run.tcl",
            sourceme.display(),
            self.output_dir.canonicalize()
                .map_err(|e| format!("Failed to canonicalize output_dir: {}", e))?
                .display()
        );

        log::info!("Executing: {}", cmd);

        let start = std::time::Instant::now();
        let status = Command::new("bash")
            .arg("-c")
            .arg(&cmd)
            .status()
            .map_err(|e| format!("Failed to execute vdbg: {}", e))?;

        if !status.success() {
            return Err("vdbg execution failed".to_string());
        }

        let elapsed = start.elapsed();

        log::info!("Workflow completed");
        log::info!("  Elapsed: {:?}", elapsed);

        // TODO: Parse UART log and exit code from vdbg output
        Ok(SimulationResult {
            exit_code: 0,
            elapsed,
            cycles: 0,
            uart_log: String::new(),
        })
    }

    fn validate_paths(&self) -> Result<(), String> {
        if !self.output_dir.exists() {
            return Err(format!("Output directory not found: {}", self.output_dir.display()));
        }

        if !self.image_path.exists() {
            return Err(format!("Image not found: {}", self.image_path.display()));
        }

        // Check if TCL template files exist
        let flash_tcl = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src/runner/0_flashbitstream/flash.tcl");
        if !flash_tcl.exists() {
            return Err(format!("flash.tcl template not found: {}", flash_tcl.display()));
        }

        let init_tcl = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src/runner/1_init/init.tcl");
        if !init_tcl.exists() {
            return Err(format!("init.tcl template not found: {}", init_tcl.display()));
        }

        let workload_tcl = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src/runner/2_runworkload/workload.tcl");
        if !workload_tcl.exists() {
            return Err(format!("workload.tcl template not found: {}", workload_tcl.display()));
        }

        Ok(())
    }

    fn generate_run_tcl(&self) -> String {
        let flash_tcl = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src/runner/0_flashbitstream/flash.tcl");
        let init_tcl = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src/runner/1_init/init.tcl");
        let workload_tcl = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("src/runner/2_runworkload/workload.tcl");

        format!(
            r#"# Main run script for P2E workflow
# Generated by bebop-p2e

set fpga_location "{}"
set ddr_channel {}
set image_path "{}"

puts "=========================================="
puts "P2E Workflow Starting"
puts "=========================================="

# Step 1: Flash bitstream
source {}
flash_bitstream $fpga_location

# Step 2: Initialize FPGA
source {}
init_fpga $fpga_location

# Step 3: Run workload
source {}
run_workload $fpga_location $ddr_channel $image_path

puts "=========================================="
puts "P2E Workflow Completed"
puts "=========================================="

exit
"#,
            self.fpga_location,
            self.ddr_channel,
            self.image_path.display(),
            flash_tcl.display(),
            init_tcl.display(),
            workload_tcl.display()
        )
    }

    fn find_sourceme(&self) -> Result<PathBuf, String> {
        // Try to find sourceme.sh in common locations
        let candidates = vec![
            PathBuf::from("sourceme.sh"),
            PathBuf::from("./sourceme.sh"),
            self.output_dir.join("../sourceme.sh"),
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sourceme.sh"),
        ];

        for path in candidates {
            if path.exists() {
                return Ok(path);
            }
        }

        Err("sourceme.sh not found. Please ensure sourceme.sh exists in the project directory".to_string())
    }
}
